name: PR Build and Publish Docker Image (Multi-Arch, SHA only)

on:
  pull_request_target:
    paths-ignore: ['*.md']
    branches: ['main']

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
            dockerfile: Dockerfile
            runner: ubuntu-latest
          - arch: arm64
            platform: linux/arm64
            dockerfile: Dockerfile.aarch64
            runner: ubuntu-24.04-arm
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Compute image vars
        id: vars
        run: |
          echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
          echo "head_sha=${{ github.event.pull_request.head.sha }}" >> "$GITHUB_OUTPUT"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by digest - ${{ matrix.arch }}
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platform }}
          # Reuse and populate BuildKit cache to speed up subsequent builds
          cache-from: type=gha,scope=sparrow-webtop-${{ matrix.arch }}
          cache-to: type=gha,scope=sparrow-webtop-${{ matrix.arch }},mode=max
          provenance: false
          sbom: false
          # Push to registry by digest only (no tags)
          outputs: type=registry,push-by-digest=true,name=ghcr.io/${{ steps.vars.outputs.owner }}/sparrow-webtop

      - name: Write digest file
        run: |
          echo "${{ steps.build.outputs.digest }}" > digest-${{ matrix.arch }}.txt

      - name: Upload digest artifact - ${{ matrix.arch }}
        uses: actions/upload-artifact@v4
        with:
          name: digest-${{ matrix.arch }}
          path: digest-${{ matrix.arch }}.txt

  manifest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute image vars
        id: vars
        run: |
          echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
          echo "head_sha=${{ github.event.pull_request.head.sha }}" >> "$GITHUB_OUTPUT"

      - name: Download digest (amd64)
        uses: actions/download-artifact@v4
        with:
          name: digest-amd64
          path: digests/amd64

      - name: Download digest (arm64)
        uses: actions/download-artifact@v4
        with:
          name: digest-arm64
          path: digests/arm64

      - name: Read digests
        id: digests
        run: |
          echo "amd64=$(cat digests/amd64/digest-amd64.txt)" >> "$GITHUB_OUTPUT"
          echo "arm64=$(cat digests/arm64/digest-arm64.txt)" >> "$GITHUB_OUTPUT"

      - name: Create and push multi-arch manifest
        run: |
          set -euo pipefail
          IMAGE="ghcr.io/${{ steps.vars.outputs.owner }}/sparrow-webtop"
          SHA_TAG="${{ steps.vars.outputs.head_sha }}"
          docker manifest create "$IMAGE:$SHA_TAG" \
            --amend "$IMAGE@${{ steps.digests.outputs.amd64 }}" \
            --amend "$IMAGE@${{ steps.digests.outputs.arm64 }}"
          docker manifest push "$IMAGE:$SHA_TAG"
